.github/workflows/stale.yml

Worflow: add stale action

---

docs/index.html

Use Github Release instead of manual release in Docs page.

docs: use Github Release

---

public/assets/logo-skizzle-dark-context.svg
src/layouts/Login/Login.scss
src/layouts/Login/Login.svelte

Adding the logo for dark mode theme

fix(Login): Logo for dark context

---

.eslintrc
.prettierrc
CONTRIBUTING.md
README.md
package.json

This pull request was made for setting up the linter, prettier and the package version

chore(Configuration): Set up linter, prettier and package version

---

src/components/Pullrequest/Pullrequest.scss
src/components/Pullrequest/Pullrequest.svelte

I changed the way Draft and Conflicts badges are displayed, so they can be displayed at the same time.
I also added the auto complete status.

Pull request status

---

public/global.css

There was a legacy CSS rule to hide scrollbar, I deleted it.

fix(Shared): Display scrollbar

---

public/electron.js
src/components/Settings/Settings.svelte

When user logs out, Electron checks for logOutRedirectUri for cleaning token, redirect to login view and close logout window.

fix(Auth): Logout modal closing

---

.github/workflows/build.yml
public/global.css
src/components/Header/Header.scss
src/components/Header/Header.svelte
src/components/Header/MacosBar.scss
src/components/Header/MacosBar.svelte
src/components/Header/WindowsBar.scss
src/components/Header/WindowsBar.svelte
src/components/MainView/MainView.scss
src/components/MainView/MainView.svelte
src/components/Profile/Profile.scss
src/components/Settings/Settings.scss
src/components/Tag/Tag.scss

This feature was maked for adapt the header bar with different environnemet (here macos and windows), for example:
Windows (Dark): 
Windows (Light):
macos (Dark): 
macos (Light):

change header bar for adapt it with the current environnement

---

src/components/ErrorMessage/ErrorMessage.scss
src/components/ErrorMessage/ErrorMessage.svelte
src/components/ErrorMessage/index.js
src/components/Profile/Profile.svelte
src/components/Settings/SettingsOrganizations.svelte
src/shared/requester.js
src/shared/store.js

I added some error messages on request failures.

fix(Requester): Added error messages when requests fails

---

src/shared/requester.js

Reset the loaded PR counter when fetching new PR

fix(Requester): fix the cloned PR and fake notifications

---

public/electron.js
src/shared/requester.js

When the getToken request fails, user is redirected to the login screen

fix(Login): Redirect to login if expired token

---

src/components/MainView/MainView.scss
src/components/MainView/MainView.svelte
src/shared/requester.js
src/shared/store.js

Checked for error code 203 when fetching pull requests

fix(Requester): Error 203

---

.github/workflows/build.yml
package.json

Remove (for a while) a macos sign processing

fix(sign): remove macos signature

---

package.json
public/splashscreen.html

refactor(public): remove unused variables

---

.gitignore
package-lock.json
package.json
public/electron.js
src/components/CommentsCounter/CommentsCounter.scss
src/components/CommentsCounter/CommentsCounter.svelte
src/components/CommentsCounter/CommentsCounter.test.js
src/components/MainView/MainView.svelte
src/components/Modal/Global/GlobalModal.scss
src/components/Modal/Global/GlobalModal.svelte
src/components/Modal/Global/index.js
src/components/Modal/Modal.scss
src/components/Modal/Modal.svelte
src/components/Modal/PullRequest/PullRequestModal.scss
src/components/Modal/PullRequest/PullRequestModal.svelte
src/components/Modal/PullRequest/PullRequestModal.test.js
src/components/Modal/PullRequest/PullRequestModal.utils.js
src/components/Modal/PullRequest/PullRequestModal.utils.test.js
src/components/Modal/PullRequest/__snapshots__/PullRequestModal.test.js.snap
src/components/Modal/PullRequest/index.js
src/components/Modal/index.js
src/components/Profile/Profile.svelte
src/components/Pullrequest/Pullrequest.scss
src/components/Pullrequest/Pullrequest.svelte
src/components/Pullrequest/Pullrequest.test.js
src/components/Pullrequest/Pullrequest.utils.js
src/shared/requester.ts
src/shared/store.ts

feat(comments): comments supports !

---

changelog-template.hbs
package-lock.json
package.json

#21 
Added auto-changelog package, script and  template
Based on [Axa group radar changelog](https://github.com/axa-group/radar/blob/master/CHANGELOG.md)

feat(changelog): added auto-changelog package, script and template

---

public/electron.js
public/updater.js

This pull request was maked for fix connection error on the beginning, it's was maked for a better life !

fix(updater): add retry pattern when application has no connection

---

public/electron.js
public/updater.js
src/shared/store.ts

When user logout, startup is now set to default value (e.g. false)

fix(startup): when user logout, startup is now set to default value 

---

public/electron.js

Disable auto update for macOS. Waiting for the Apple account for enabling it.

feat(auto update): disable for macOS

---

src/components/CommentsCounter/CommentsCounter.scss
src/components/CommentsCounter/CommentsCounter.svelte
src/components/Pullrequest/Pullrequest.svelte

Click on PR opens now Azure PR page. Click on comments counter opens comments modal.

fix(pull request): button for comments display

---

src/components/Event/Halloween/Skeleton/Spider.scss
src/components/Event/Halloween/Skeleton/Spider.svelte
src/components/Event/Halloween/Skeleton/index.js
src/components/ListHeader/ListHeader.svelte

Added more Halloween easter egg!
A spider will appear every 1min for 3sec 🎃🎃

More Halloween easter egg

---

package-lock.json
package.json
src/App.svelte
src/components/ErrorBoundary/ErrorBoundary.svelte
src/components/ErrorBoundary/index.ts
src/components/Main/Main.svelte
src/electron/electron.ts

Displays error boundary component every time JavaScript Crashes

feat(all): error boundary

---

src/App.svelte
src/components/AccountSummary/AccountSummary.svelte
src/components/AzureDevOps/AzureDevOps.svelte
src/components/Github/Github.svelte
src/components/Notification/Notification.svelte
src/components/Search/Search.svelte
src/components/Settings/Settings.svelte
src/components/Tabs/Tabs.svelte
src/components/icons/ArrowLeft.svelte
src/components/icons/ArrowRight.svelte
src/components/icons/index.ts
src/shared/stores/default.store.ts
src/shared/stores/store.ts
src/views/Intro/Intro.svelte
src/views/Intro/index.ts

Adds intro for new users to allow them to connect providers accounts and follow repositories.

feat(all): intro

---

package-lock.json
src/App.svelte
src/components/CustomListSettings/CustomListSettings.svelte

Fixing title on custom list tab and more

fix(customList): fixing title on custom list tab and more

---

docs/index.html
docs/styles.css

Fix the website download url. Also changes the download buttons labels following user's operating system.

fix(site): fix download url

---

docs/index.html

fix(docs): release url

---

docs/index.html
docs/styles.css

Fixed website display on small screens.

fix(docs): responsive

---

CHANGELOG.md
package.json
src/components/Settings/Settings.svelte

Hide update field when application restart

fix(Update): hide update field when application restart

---

src/components/Button/Button.svelte
src/components/Button/index.ts
src/components/CustomListSettings/CustomListSettings.svelte
src/components/ImportExport/ImportExport.svelte
src/components/Settings/Settings.svelte

Create reusable Button component

refactor: button reusable component

---

docs/index.html
docs/styles.css

- Augment buttons contrast.
- Disable decoration images for screen readers.

feat: improve website accessibility

---

package.json
src/components/Button/Button.svelte
src/components/FollowedRepositories/FollowedRepositories.svelte
src/components/ImportExport/ImportExport.svelte

Export modale can now scroll properly.

fix: export modale scroll
